### ISSUE TITLE
Configuración de la capa de base de datos ORM

### ISSUE THREAD

**Issue by hectormateos** [xavism/nestjs-cars-crud#2]
Buenas Xavi! ¿Cómo estás?
Estuve el jueves pasado en tu charla de nest.js y tengo mucho interés en aprender sobre este framework.
Estoy intentando poner en marcha los dos repos que preparaste, me van a ser super útiles, y simplemente quería preguntarte o pedirte el esquema de mysql (la tabla User, etc.) que has utilizado para montarlo bien por completo.
Muchas gracias por la charla y por tu atención!
Un saludo!

**Comment by xavism** [comment]
Hola hector! No necesitas el esquema. Solo un mysql al que apuntar y una
base de datos. Pones las configuraciones en el archivo de typeorm (en la
raiz del proyecto) y las tablas se  crearan al ejecutar con npm start.

Saludos!

**Comment by hectormateos** [comment]
Fenomenal Xavi, muchas gracias!
